version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - './app:/var/www/propellerads'
    depends_on:
      - redis

  redis:
    image: redis:7.0.8

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '7777:80'
    volumes:
      - './app:/var/www/propellerads'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - redis
